---
- name: Gather installed packages
  package_facts:
    manager: auto

- name: Check if Zabbix Agent 2 installed
  set_fact:
    zabbix_agent2_installed_version: "{{ ansible_facts.packages['zabbix-agent2'][0]['version'] | default('0') }}"
  when: "'zabbix-agent2' in ansible_facts.packages"

- name: Set default version if Zabbix agent not installed
  set_fact:
    zabbix_agent2_installed_version: "0"
  when: "'zabbix-agent2' not in ansible_facts.packages"

- name: Determine if upgrade is needed
  set_fact:
    zabbix_agent2_needs_upgrade: "{{ (zabbix_agent2_installed_version | default('0')) == '0' or (zabbix_agent2_installed_version is version(zabbix_target_version, '<')) }}"

- name: Define Zabbix repo package URL
  set_fact:
    zabbix_repo_url: "https://repo.zabbix.com/zabbix/{{ zabbix_target_version }}/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_target_version }}+ubuntu{{ ansible_distribution_version }}_all.deb"
  when: ansible_distribution == 'Ubuntu'

- name: Download and install Zabbix repo if needed
  apt:
    deb: "{{ zabbix_repo_url }}"
    update_cache: yes
    state: present
  when: zabbix_agent2_needs_upgrade

- name: Ensure latest Zabbix Agent 2 from {{ zabbix_target_version }} is installed
  apt:
    name: zabbix-agent2
    state: latest
    update_cache: yes
  when: zabbix_agent2_needs_upgrade
