---
- name: Set hostname as the environment name
  shell: "hostnamectl set-hostname {{ item.key }}"
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Get hostname
  shell: hostname
  register: zabbix_hostname

- name: Install Zabbix repository package and update apt cache
  apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb"
    update_cache: yes
    state: present

- name: Install Zabbix Agent 2
  apt:
    name: zabbix-agent2
    state: latest
    update_cache: yes

- name: Copy agent2 configuration file
  template:
    src: zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.d/agent.conf
    owner: root
    group: root
    mode: '0644'

- name: Create PSK file
  lineinfile:
    path: /etc/zabbix/zabbix_agentd2.psk
    line: "{{ zabbix_psk_key }}"
    create: yes
  no_log: yes

- name: Enable and Restart Zabbix to apply new configuration
  systemd:
    name: zabbix-agent2
    state: restarted
    enabled: yes
