---
- name: Set hostname as the environment name
  shell: "hostnamectl set-hostname {{ item.key }}"
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: trellis_enabled | default(true) | bool

- name: Get hostname
  shell: hostname
  register: zabbix_hostname

- name: Gather facts about the OS
  setup:

- name: Install Zabbix repository package and update apt cache
  apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb"
    update_cache: yes
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Install Zabbix repository package and update apt cache
  apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb"
    update_cache: yes
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '22.04'

- name: Install Zabbix Agent 2
  apt:
    name: zabbix-agent2
    state: latest
    update_cache: yes

- name: Copy agent2 configuration file
  template:
    src: zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.d/agent.conf
    owner: root
    group: root
    mode: '0644'

- name: Create PSK file
  lineinfile:
    path: /etc/zabbix/zabbix_agentd2.psk
    line: "{{ zabbix_psk_key }}"
    create: yes
  no_log: yes

- name: Detect php version
  shell: |
    php -v | grep -oP 'PHP\s+\K\d+\.\d+' | head -n1
  register: php_detected_version

- name:
  block:

    - name: Add fpm ini configuration params to enable status for FPM + nginx
      ini_file: dest="/etc/php/{{ php_detected_version.stdout }}/fpm/pool.d/wordpress.conf" section=wordpress option="{{ item.option }}" value="{{ item.value }}"
      with_items:
        - { option: pm.status_path, value: /status }
        - { option: ping.path, value: /ping }

    - name: Add nginx block to enable status and ping
      blockinfile:
        path: "/etc/nginx/sites-available/{{ zabbix_hostname.stdout }}.conf"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        insertafter: "EOF"
        block: |
          server {
            listen [::]:80;
            listen 80;
            server_name localhost;
            # Enable php-fpm status page
            location ~ ^/(status|ping)$ {
              ## disable access logging for request if you prefer
              access_log off;

              ## Only allow trusted IPs for security, deny everyone else
              allow 127.0.0.1;
              allow ::1;
              deny all;

              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
              fastcgi_index index.php;
              fastcgi_pass unix:/var/run/php-fpm-wordpress.sock;
            }
          }

    - name: Test nginx config
      shell: "nginx -t"
      register: nginx_is_reloadable
      ignore_errors: yes

    - name: DO - Nginx reload
      systemd:
        name: nginx
        state: reloaded
      when: nginx_is_reloadable is defined and "/etc/nginx/nginx.conf syntax is ok" in nginx_is_reloadable.stderr and "/etc/nginx/nginx.conf test is successful" in nginx_is_reloadable.stderr
  
  when: php_detected_version.stdout is defined and "not found" not in php_detected_version.stderr

- name: Detect MariaDB/MySQL
  shell: "systemctl is-active mariadb"
  register: mariadb_installed
  ignore_errors: yes

- name: Execute only if Mysql/MariaDB is installed
  block:

    - name: Create Zabbix user and grant permissions to the DB engine
      mysql_user:
        name: zbx_monitor
        host: "%"
        password: "{{ zabbix_mysql_monitor_password }}"
        priv: "*.*:REPLICATION CLIENT,PROCESS,SHOW DATABASES,SHOW VIEW"
        state: present
        login_user: root
        login_password: "{{ vault_mysql_root_password }}"

  when: '"inactive" not in  mariadb_installed.stdout'

- name: Enable and Restart Zabbix to apply new configuration
  systemd:
    name: zabbix-agent2
    state: restarted
    enabled: yes
